### ISSUE TITLE
Question: why do `data_augmentation` function never apply the `data_augmentation_layers`?

### ISSUE THREAD

**Issue by 2320sharon** [mlundine/ShorelineFilter#1]
In both `image_filter.py` and  `image_segmentation_filter.py` the data augmentation function never applies the `data_augmentation_layers`, why is this?
```
def data_augmentation(images):
    """
    applies data augmentation to images
    """
    data_augmentation_layers = [
        layers.RandomFlip("horizontal"),
        layers.RandomFlip("vertical"),
        layers.RandomRotation(0.25),
        layers.RandomZoom(0.5, 0.5),
        
    ]
    return images
```

**Comment by mlundine** [comment]
Those get called as the first layer in the model, see define_model().

**Comment by 2320sharon** [comment]
![image](https://github.com/user-attachments/assets/8410d2c6-8f44-4926-989c-334632a9c44c)
I see that these get called as the first layer in the model, but since data_augmentation_layers are  not returned by the data_augmentation function they aren't being used to create the first layer

**Comment by mlundine** [comment]
oof good catch, let me fix that

**Comment by 2320sharon** [comment]
Thank you!
